# Generated by Django 4.1 on 2023-09-22 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tf_20230920',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ApplicationId', models.IntegerField(null=True)),
                ('ApplicationDate', models.DateTimeField()),
                ('IdRow', models.IntegerField()),
                ('AccountId', models.CharField(max_length=255)),
                ('Balance', models.FloatField()),
                ('Bank', models.CharField(max_length=255)),
                ('transactionDate', models.DateTimeField()),
                ('transactionAmount', models.FloatField()),
                ('transactionClass', models.CharField(max_length=100)),
                ('transactionDescription', models.TextField()),
                ('predictedCategoryDescription', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
