# Generated by Django 4.1 on 2023-10-05 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tf_20230920',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
