# Generated by Django 4.1 on 2023-10-05 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_tf_20230920_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tf_20230920',
            name='ApplicationDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tf_20230920',
            name='transactionDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
